version: "3.8"

services:
    web:
        image: noob_mvc # CHANGE
        build: ./web
        restart: always
        depends_on:
            - db
        ports:
            - 52080:80 # CHANGE
        networks:
            - web-db
        volumes:
            - .\web:/var/www/html/
        secrets:
            - DB_NAME
            - DB_SERVER
            - DB_USERNAME_SELECT
            - DB_PASS_SELECT
            - DB_USERNAME_INSERT
            - DB_PASS_INSERT
            - DB_USERNAME_UPDATE
            - DB_PASS_UPDATE
            - DB_USERNAME_DELETE
            - DB_PASS_DELETE
        environment:
            - TZ=CET # CHANGE
            - ERROR_REPORTING=1

    db:
        image: mvc_template # CHANGE
        build: ./db
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --secure-file-priv="/run/secrets"
        networks:
            - web-db
            - admin-db
        volumes:
            - mvc_db:/var/lib/mysql # CHANGE
        secrets:
            - DB_NAME
            - DB_USERNAME_ROOT
            - DB_PASS_ROOT
            # NEED SOLUTION FOR FOLLOWING SECRETS
            - DB_USERNAME_SELECT
            - DB_PASS_SELECT
            - DB_USERNAME_INSERT
            - DB_PASS_INSERT
            - DB_USERNAME_UPDATE
            - DB_PASS_UPDATE
            - DB_USERNAME_DELETE
            - DB_PASS_DELETE
        environment:
            - TZ=CET # CHANGE
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_PASS_ROOT
            - MYSQL_DATABASE_FILE=/run/secrets/DB_NAME

    phpmyadmin:
        image: phpmyadmin:5.0-apache
        depends_on:
            - db
        ports:
            - 51080:80 # CHANGE
        networks:
            - admin-db
        secrets:
            - DB_NAME
            - DB_PASS_ROOT
            - DB_USERNAME_ROOT
        environment:
            - TZ=CET # CHANGE
            - PMA_HOST_FILE=/run/secrets/DB_NAME
            - PMA_USER_FILE=/run/secrets/DB_USERNAME_ROOT
            - PMA_PASSWORD_FILE=/run/secrets/DB_PASS_ROOT

networks:
    web-db:
    admin-db:

volumes:
    mvc_db: # CHANGE

secrets:
    DB_NAME:
        file: ./secrets/DB_NAME
    DB_SERVER:
        file: ./secrets/DB_SERVER
    DB_USERNAME_ROOT:
        file: ./secrets/DB_USERNAME_ROOT
    DB_PASS_ROOT:
        file: ./secrets/DB_PASS_ROOT
    DB_USERNAME_SELECT:
        file: ./secrets/DB_USERNAME_SELECT
    DB_PASS_SELECT:
        file: ./secrets/DB_PASS_SELECT
    DB_USERNAME_INSERT:
        file: ./secrets/DB_USERNAME_INSERT
    DB_PASS_INSERT:
        file: ./secrets/DB_PASS_INSERT
    DB_USERNAME_UPDATE:
        file: ./secrets/DB_USERNAME_UPDATE
    DB_PASS_UPDATE:
        file: ./secrets/DB_PASS_UPDATE
    DB_USERNAME_DELETE:
        file: ./secrets/DB_USERNAME_DELETE
    DB_PASS_DELETE:
        file: ./secrets/DB_PASS_DELETE
