-- use db;  -- CHANGE DB NAME HERE + in USERS CREATION

CREATE TABLE test(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    test varchar(5)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- USE SECRETS FOR DB_NAME & USERNAMES! HOW TO USE FILES STRING IN CREATE USER?
CREATE USER 'SELECTOR'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
GRANT SELECT ON db.* TO 'SELECTOR'@'%';

CREATE USER 'INSERTOR'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
GRANT INSERT ON db.* TO 'INSERTOR'@'%';

CREATE USER 'UPDATOR'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
GRANT SELECT, UPDATE ON db.* TO 'UPDATOR'@'%';

CREATE USER 'DELETOR'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
GRANT SELECT, DELETE ON db.* TO 'DELETOR'@'%';